version: '3.4'

services:
    api:
        image: steamtrader/api-dev-service
        depends_on:
            - postgres
            - seq
        environment:
          - SEQ=dev_seq
        networks:
          - backend
    postgres:
        image: postgres:13-alpine
        environment:
           - POSTGRES_PASSWORD=password
    seq:
        image: datalust/seq
        environment:
           - ACCEPT_EULA=Y
        networks:
           - traefik-public
           - backend
        deploy:
          labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.constraint-label=traefik-public
            - traefik.http.routers.dev_seq-http.rule=Host(`${DOMAIN?Variable not set}`)
            - traefik.http.routers.dev_seq-http.entrypoints=http
            - traefik.http.routers.dev_seq-http.middlewares=https-redirect
            - traefik.http.routers.dev_seq-https.rule=Host(`${DOMAIN?Variable not set}`)
            - traefik.http.routers.dev_seq-https.entrypoints=https
            - traefik.http.routers.dev_seq-https.tls=true
            - traefik.http.routers.dev_seq-https.tls.certresolver=le
            - traefik.http.services.dev_seq.loadbalancer.server.port=80
networks:
    traefik-public:
       external: true
    backend: